CREATE TABLE users (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, password TEXT NOT NULL);"
CREATE TABLE projects (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT NOT NULL, user_id INTEGER);"
CREATE TABLE tasks (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT NOT NULL, time INTEGER, date DATE, project_id INTEGER, activity_id INTEGER);
CREATE TABLE activities (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
INSERT INTO `activities` (`name`) VALUES ('Self development');
INSERT INTO `activities` (`name`) VALUES ('Working time');
INSERT INTO `activities` (`name`) VALUES ('Extra time');
INSERT INTO `activities` (`name`) VALUES ('Team time');
INSERT INTO `users` (`name`,`password`) VALUES ('q','q');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('1 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('2 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('3 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('4 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('5 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('6 project','description','1');
INSERT INTO `projects` (`name`,`description`,`user_id`) VALUES ('N/A','description','1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Drink Cola','description','124','2012-03-14', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('saving the world','description','524','2012-03-14', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Fixing bug','description','224','2012-03-15', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Creating app','description','324','2012-03-16', '1', '2');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Back to the future','description','444','2012-03-15', '1', '2');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Trip to the moon','description','600','2012-03-15', '1', '3');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Exploring black hole','description','90','2012-03-15', '1', '3');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Lorem ipsum','description','124','2012-03-17', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Sit amet','description','524','2012-03-17', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Consectetur','description','224','2012-03-17', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Adipisicing','description','124','2012-03-18', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Elit','description','524','2012-03-18', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Natus','description','224','2012-03-18', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Quia','description','124','2012-03-19', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Dignissimos','description','524','2012-03-19', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Ducimus','description','224','2012-03-19', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Officia','description','124','2012-03-20', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Laborum','description','524','2012-03-20', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Impedit','description','224','2012-03-20', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Minus','description','124','2012-03-21', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Minima','description','524','2012-03-21', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Maxime','description','224','2012-03-21', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Voluptates','description','124','2012-04-16', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Consequatur','description','524','2012-04-16', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Repudiandae','description','224','2012-04-16', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Harum','description','124','2012-03-22', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Nemo','description','524','2012-03-22', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Porro','description','224','2012-03-22', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Dicta','description','124','2012-03-23', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Reprenederit','description','524','2012-03-23', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Nulla','description','224','2012-03-23', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Mollit','description','124','2012-03-24', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Sunt','description','524','2012-03-24', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Culpa','description','224','2012-03-24', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Laborum','description','124','2012-03-25', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Deserunt','description','524','2012-03-25', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Proident','description','224','2012-03-25', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Drink Cola','description','124','2012-03-26', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Dolores','description','524','2012-03-26', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Cupidiate','description','224','2012-03-26', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Odio','description','124','2012-03-27', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Corrupti','description','524','2012-03-27', '1', '1');
INSERT INTO `tasks` (`name`,`description`,`time`,`date`,`project_id`,`activity_id`) VALUES ('Quidem','description','224','2012-03-27', '1', '1');
